(("src" . ((nil . ((dante-target . "language-kit")))))
 ("lang" . ((nil . ((dante-target . "lang")))))
 ("structure/term" . ((nil . ((dante-target . "structure-term")))))
 ("structure/pattern" . ((nil . ((dante-target . "structure-pattern")))))
 ("structure/type" . ((nil . ((dante-target . "structure-type")))))
 ("structure/data" . ((nil . ((dante-target . "structure-data")))))
 ("structure/kind" . ((nil . ((dante-target . "structure-kind")))))
 ("rule/eval" . ((nil . ((dante-target . "rule-eval")))))
 ("rule/pattern" . ((nil . ((dante-target . "rule-pattern")))))
 ("fragment/int" . ((nil . ((dante-target . "fragment-int")))))
 ("fragment/bool" . ((nil . ((dante-target . "fragment-bool")))))
 ("fragment/eq-int" . ((nil . ((dante-target . "fragment-eq-int")))))
 ("fragment/stlc" . ((nil . ((dante-target . "fragment-stlc")))))
 ("lang/ibe" . ((nil . ((dante-target . "lang-ibe")))))
)
